name: ohuac
version: '0.3.0'
category: Devel
author: Sebastian Ertel, Justus Adam
maintainer: dev@justus.science
copyright: © 2017, 2018 Sebastian Ertel, Justus Adam
license: OtherLicense
github: ohua-dev/ohuac
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NoImplicitPrelude
- TypeApplications
- NamedFieldPuns
- RecordWildCards
- RankNTypes
- ViewPatterns
- NoImplicitPrelude
- StandaloneDeriving
dependencies:
- base
- ohua-core >= 0.3.0
- bytestring
- aeson
- filepath
- directory
- template-haskell
- unordered-containers
- lens
- monad-control
library:
  source-dirs: src/hs
  dependencies:
  - async
  - mtl
  - text
  - recursion-schemes
  - lifted-async
  - containers
  - casing
  - language-java
  when:
    - condition: flag(with-clike-parser)
      dependencies:
      - alang-clike-parser
      cpp-options:
      - -DWITH_CLIKE_PARSER=1
    - condition: flag(with-sexpr-parser)
      dependencies:
      - alang-sexpr-parser
      cpp-options:
      - -DWITH_SEXPR_PARSER=1
    - condition: flag(with-ml-parser)
      dependencies:
      - alang-ml-parser
      cpp-options:
      - -DWITH_ML_PARSER=1
    - condition: flag(with-stdlib)
      cpp-options:
      - -DWITH_STDLIB=1
executables:
  ohuac:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ohuac
    - optparse-applicative
    - time
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

flags:
  with-sexpr-parser:
    default: true
    manual: false
  with-clike-parser:
    default: true
    manual: false
  with-ml-parser:
    default: true
    manual: false
  with-stdlib:
    default: true
    manual: false
    description:
      Compile and embed the standard library (needs `with-ml-parser` to be
      enabled)
tests:
  ohua-standalone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
