name: ohuac
version: '0.1.0'
category: Devel
author: Sebastian Ertel, Justus Adam
maintainer: dev@justus.science
copyright: © 2017 Sebastian Ertel, Justus Adam
license: OtherLicense
github: ohua-dev/ohua-standalone
extra-source-files:
- README.md
# library:
#   source-dirs: src
#   exposed-modules:
#   - Lib
#   dependencies:
#   - base >=4.7 && <5
#   - ohua-core
default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NoImplicitPrelude
- TypeApplications
- NamedFieldPuns
- RecordWildCards
- RankNTypes
- ViewPatterns
- NoImplicitPrelude
- StandaloneDeriving
dependencies:
- protolude
- base
- microlens
- microlens-platform
- ohua-core
- bytestring
- aeson
- filepath
- directory
- data-default-class
- protolude
library:
  source-dirs: src
  dependencies:
  - async
  - mtl
  - text
  - recursion-schemes
  - lifted-async
  - uniplate
  - unordered-containers
  - containers
  - casing
  - language-java
  when:
    - condition: flag(with-clike-parser)
      dependencies:
      - alang-clike-parser
      cpp-options:
      - -DWITH_CLIKE_PARSER=1
    - condition: flag(with-sexpr-parser)
      dependencies:
      - alang-sexpr-parser
      cpp-options:
      - -DWITH_SEXPR_PARSER=1
executables:
  ohuac:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ohuac
    - optparse-applicative
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

flags:
  with-sexpr-parser:
    default: true
    manual: false
  with-clike-parser:
    default: false
    manual: true
tests:
  ohua-standalone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
