resolver: lts-12.5
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 4385684f0eb96105da83f2779e743e39774f216a
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: 305290fbf38550c7252d88ee6b4b35f53b31303c
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: 845eeaefebca81c97b87a26e234fb682f6c03251
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: true
    with-sexpr-parser: true
extra-package-dbs: []
