resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: c41e558ec6a4041c573afd22782d5098cc70c16
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: bcb347d65c80d5fd57b06f38d3c032bca8f8fbd
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: 4d97879b1f107d969d4c2d602d86dd535cd9bdd
  extra-dep: true
extra-deps: [exit-codes-0.1.1.0]
flags:
  ohuac:
    with-clike-parser: yes
    with-sexpr-parser: yes
extra-package-dbs: []
