resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 75803248998933fd9a8e4f1172fe4c93e0c3bb61
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: 22a4653de796ba62a51f7feda8b5a6932c3fcc95
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: 4d91eddae36c8cc02215d76bbe2bdf0387b9a7ea
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-ml-parser
    commit: 17ad1606549984ddd68bc6a0a2d0d074ae9b8be5
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: yes
    with-sexpr-parser: yes
    with-ml-parser: yes
extra-package-dbs: []
