resolver: lts-9.3
packages:
- .
- location:
    git: git@github.com:ohua-dev/ohua-core
    commit: 32e06a06cf5dbb8a66397ce674b874273f0576ce
  extra-dep: true
- location:
    git: git@github.com:ohua-dev/alang-clike-parser
    commit: 2b35c741a362dbad20c2bf17b62161ffb210fa22
  extra-dep: true
- location:
    git: git@github.com:ohua-dev/alang-sexpr-parser
    commit: 40b3370d080db3bb075d0dbef31e7f7fcd5ddc78
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: true
    with-sexpr-parser: true
extra-package-dbs: []
