resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: cc55e0fe5737311a1657e7ac1df2e93294e79f45
  subdirs: [core]
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: cf0cd6b2d1cd72d7cdfeda896aacf7d3e141bdf8
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: fdc81f8c8c2fef63e7a306c2a323e3919b0d88ca
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-ml-parser
    commit: ffb856ac7f60e83689324f8d6b8334bb8f898159
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: yes
    with-sexpr-parser: yes
    with-ml-parser: yes
  ohua-core:
    debug: true
extra-package-dbs: []
