resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: f29a82cd8119a26ddd443324f4509d9c55e4e92f
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: a8bd94972aaad02c8a6587684c7406d3014ddd19
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: a5391f20bb5b3448f23403f9d88792f46746f982
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: yes
    with-sexpr-parser: yes
extra-package-dbs: []
