resolver: lts-10.4
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 078a3b3b5a732e6fbf58afc5c7945014e5a4eda4
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: afeb737d1d7e64c7da8ace3983136365201a484c
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: 40b3370d080db3bb075d0dbef31e7f7fcd5ddc78
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: true
    with-sexpr-parser: true
extra-package-dbs: []
