resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 843bcdca4abc1393076e3ae69d750af095ed7d59
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-clike-parser
    commit: 33170482ff9eb3cf44ba61d11384c059e1fefe4f
  extra-dep: true
- location:
    git: https://github.com/ohua-dev/alang-sexpr-parser
    commit: a5391f20bb5b3448f23403f9d88792f46746f982
  extra-dep: true
extra-deps: []
flags:
  ohuac:
    with-clike-parser: yes
    with-sexpr-parser: yes
extra-package-dbs: []
